import { SITE_URL } from '../../lib/seo';

export const dynamic = 'force-static';

export function GET() {
  const body = [
    '# Qognition Agency — robots.txt',
    '# https://www.qognitionagency.com',
    '',
    '# ── Standard crawlers ────────────────────────────────────────',
    'User-agent: *',
    'Allow: /',
    'Disallow: /api/',
    'Disallow: /legal/',
    '',
    '# ── AI / LLM crawlers ────────────────────────────────────────',
    '# OpenAI — ChatGPT, SearchGPT',
    'User-agent: GPTBot',
    'Allow: /',
    '',
    'User-agent: OAI-SearchBot',
    'Allow: /',
    '',
    'User-agent: ChatGPT-User',
    'Allow: /',
    '',
    '# Anthropic — Claude',
    'User-agent: Claude-Web',
    'Allow: /',
    '',
    'User-agent: anthropic-ai',
    'Allow: /',
    '',
    'User-agent: ClaudeBot',
    'Allow: /',
    '',
    '# Perplexity',
    'User-agent: PerplexityBot',
    'Allow: /',
    '',
    '# Google AI',
    'User-agent: GoogleOther',
    'Allow: /',
    '',
    'User-agent: Google-Extended',
    'Allow: /',
    '',
    '# Apple',
    'User-agent: AppleBot',
    'Allow: /',
    '',
    '# Common Crawl (training data)',
    'User-agent: CCBot',
    'Allow: /',
    '',
    '# Cohere',
    'User-agent: cohere-ai',
    'Allow: /',
    '',
    '# Meta',
    'User-agent: FacebookBot',
    'Allow: /',
    '',
    '# Bytedance / TikTok',
    'User-agent: Bytespider',
    'Allow: /',
    '',
    '# Internet Archive',
    'User-agent: ia_archiver',
    'Allow: /',
    '',
    '# ── Sitemaps ─────────────────────────────────────────────────',
    `Sitemap: ${SITE_URL}/sitemap.xml`,
    `Sitemap: ${SITE_URL}/sitemaps/core.xml`,
    `Sitemap: ${SITE_URL}/sitemaps/spokes.xml`,
    `Sitemap: ${SITE_URL}/sitemaps/services.xml`,
    `Sitemap: ${SITE_URL}/sitemaps/blog.xml`,
    `Sitemap: ${SITE_URL}/sitemaps/case-studies.xml`,
    '',
    '# ── LLM Discovery ────────────────────────────────────────────',
    `# LLMs.txt: ${SITE_URL}/llms.txt`,
    `# LLMs-full: ${SITE_URL}/llms-full.txt`,
    '',
  ].join('\n');

  return new Response(body, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 's-maxage=3600, stale-while-revalidate=86400',
    },
  });
}
